// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pujas.Infraestructura.Persistencia;

#nullable disable

namespace Pujas.Infraestructura.Migrations
{
    [DbContext(typeof(App_Db_Context))]
    [Migration("20250628210843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pujas.Dominio.Entidades.Puja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha_Puja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<string>("Id_Postor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Id_Postor");

                    b.Property<string>("Id_Subasta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Id_Subasta");

                    b.Property<decimal>("Incremento")
                        .HasColumnType("numeric")
                        .HasColumnName("Incremento");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("Monto");

                    b.HasKey("Id");

                    b.ToTable("Subasta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
